name: Multi-Cloud Master Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # This is the "Key" for the warehouse
      id-token: write  # This helps with secure connections


    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Check System Info
        run: hostnamectl

      # --- LOGINS ---
      - name: 3. Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 4. Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

            # --- BUILD AND MULTI-PUSH ---
      - name: 5. Build and Push to All
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Note: The tags below must have EXACTLY 12 spaces before them
          tags: |
            ghcr.io/agwu-monica/netflix-backend:latest
            ${{ secrets.AZURE_REGISTRY_SERVER }}/netflix-backend:latest
