name: Docker-build-and-push (Manual)

on:
  push:
    branches: [ "main" ]

jobs:
  manual-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 1. Grab code
        uses: actions/checkout@v4

      - name: 2. Check System Info (Hostnamectl)
        run: hostnamectl

      - name: 3. Login to GitHub Storage (Manual)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 4. Build the Image (Manual)
        run: docker build -t ghcr.io/agwu-monica/netflix-backend:latest .

      - name: 5. Push the Image (Manual)
        run: docker push ghcr.io/agwu-monica/netflix-backend:latest
